### ISSUE TITLE
Mild request on code review written in pytorch

### ISSUE THREAD

**Issue by deepshwang** [ShiQiu0419/BAAF-Net#10]
Hello,

I have been doing projects on implementing your code on PyTorch, and the link is here 

https://github.com/deepshwang/BAAF-pytorch

However, the model I coustructed is not converging, and is in process of debugging it...

I know it's a tedious and time-consuming to review other's code, but wish you may review the model if you have some free time.. :)

Many thanks to your outstanding work!

**Comment by ShiQiu0419** [comment]
Wow, many thanks for your efforts. However, I may not be able to carefully review it in a near future since currently I am writing 2 papers. Maybe I could have some free time in mid of August..

In my opinion, it is always tricky to set up a sucessful re-implementation if you build it from scratch (because I am not an expert in tuning the hyper-parameters...). In an easier way, I suggest you to adopt a good framework and only re-implement the network part. Personally, I think [CloserLook3D](https://github.com/zeliu98/CloserLook3D/tree/master/pytorch) is a good choice, which shares a similar pipeline as RandLA-Net and our BAAF-Net.

**Comment by deepshwang** [comment]
Thanks a lot! I will definitely have to look into the repo you recommended.
