### ISSUE TITLE
An error was reported about running

### ISSUE THREAD

**Issue by liasy-0** [ShiQiu0419/BAAF-Net#23]
Hello, I ran the test area5 in the process of replicating, and the code reported an attributeerror: type object 'iteratorbase' has no attribute 'from_structure, may I ask how to solve it? I have been troubled for a long time. Thank you for your reply, including the result of your repetition, can you open and display no coordinate information?，thank you

**Comment by ShiQiu0419** [comment]
Thank you for your interests in our project. I presume that the issue is caused by the different versions of TF and CUDA, since our project is based on the old Tensorflow 1.13.1 and cuda 10.0. If you want to successfully run the codes, you may set up a virtual environment using these specific versions.

I plan to extend our BAAF-Net using recent OpenPoints library with PyTorch later this year, please stay tuned.

**Comment by liasy-0** [comment]
thank you
