### ISSUE TITLE
不同版本的cuda报错

### ISSUE THREAD

**Issue by yangpanquan** [ShiQiu0419/BAAF-Net#3]
作者，您好，请问我在win10下用cuda10.2和cudnn7.6跑代码，S3DIS数据预处理那个文件报错ImportError: DLL load failed: 找不到指定的模块。我找了半天觉得就是cuda调用那块，所以您觉得是什么出问题了呢？

**Comment by ShiQiu0419** [comment]
Hi @yangpanquan ,

I did not encounter this issue since the data pre-processing was also operated on Linux. I am sorry that I have no windows-based machine with GPU. Basically, the pre-processing codes are from [RandLA-Net](https://github.com/QingyongHu/RandLA-Net), you can directly use the same data if you had successfully run the RandaLA-Net repo before. Otherwise, you may refer to the similar issues there.

Cheers,
Shi

**Comment by yangpanquan** [comment]
Thank you, I will try to run the RandLA-Net，and see whether it can work

**Comment by 1981672112** [comment]
你好，请问randla调通了没？我调不通
